### ISSUE TITLE
[Reporte]

### ISSUE THREAD

**Issue by German858** [Flussen/road_to_56_spanish#2]
**Describe el bug**
Una descripción clara y concisa del bug, error o a mejorar.

**Reproducir**
Cómo se reproduce este problema?

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperabas que ocurriera.

**Capturas de pantalla**
Si es aplicable, agrega capturas de pantalla para explicar tu problema.

**Escritorio (por favor completa la siguiente información):**
 - SO: [e.g Linux, Windows, Mac]
 - Versión HOI4 [e.g. 1.14.5]
 - Versión de ESTE mod [e.g. 0.1]

**Contexto adicional**
Agrega cualquier otro contexto sobre el problema aquí. *(Opcional)*

**Comment by Flussen** [comment]
Agrega por favor más detalle!
